name = "acearchive-files"
main = "./src/index.ts"
compatibility_date = "2022-10-04"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[env.prod]

  [env.prod.route]
  pattern = "files.acearchive.lgbt"
  custom_domain = true

  [env.prod.vars]
  ARCHIVE_URL = "https://acearchive.lgbt"
  BASE_URL = "https://files.acearchive.lgbt"

  [[env.prod.d1_databases]]
  binding = "DB"
  database_name = "acearchive-artifacts"
  database_id = "ffd316de-0455-429b-90c7-45f935183333"
  preview_database_id = "12b24516-946d-4ebd-abbb-8db821159924"

  [[env.prod.r2_buckets]]
  binding = "PRIMARY_BUCKET"
  bucket_name = "acearchive-lgbt-artifacts"
  preview_bucket_name = "acearchive-lgbt-artifacts-dev"

[env.dev]

  [env.dev.route]
  pattern = "files-dev.acearchive.lgbt"
  custom_domain = true

  [env.dev.vars]
  ARCHIVE_URL = "https://dev.acearchive.lgbt"
  BASE_URL = "https://files-dev.acearchive.lgbt"

  [[env.dev.d1_databases]]
  binding = "DB"
  database_name = "acearchive-artifacts-dev"
  database_id = "12b24516-946d-4ebd-abbb-8db821159924"
  preview_database_id = "12b24516-946d-4ebd-abbb-8db821159924"

  [[env.dev.r2_buckets]]
  binding = "PRIMARY_BUCKET"
  bucket_name = "acearchive-lgbt-artifacts-dev"
  preview_bucket_name = "acearchive-lgbt-artifacts-dev"

  # In the dev environment, if an artifact isn't found in the dev bucket, we
  # search for it in the prod bucket instead. This saves us from having to
  # needlessly backpopulate the dev bucket when objects from submitted artifacts
  # are added to the prod bucket.
  [[env.dev.r2_buckets]]
  binding = "SECONDARY_BUCKET"
  bucket_name = "acearchive-lgbt-artifacts"
  preview_bucket_name = "acearchive-lgbt-artifacts"
